const MANTRA_MODULES={
"3-4-3":[["P"],["DC","DC","DC/B"],["E","M/C","C","E"],["W/A","W/A"],["A/PC"]],
"3-4-1-2":[["P"],["DC","DC","DC/B"],["E","M/C","C","E"],["T"],["A/PC","A/PC"]],
"3-4-2-1":[["P"],["DC","DC","DC/B"],["M","M/C","E"],["E/W"],["T","T/A"],["A/PC"]],
"3-5-2":[["P"],["DC","DC","DC/B"],["E/W","M/C","M","C","E"],["A/PC","A/PC"]],
"3-5-1-1":[["P"],["DC","DC","DC/B"],["E/W","M","C","M","E/W"],["T/A"],["A/PC"]],
"4-3-3":[["P"],["DD","DC","DC","DS"],["M/C","M","C"],["W/A","W/A"],["A/PC"]],
"4-3-1-2":[["P"],["DD","DC","DC","DS"],["M/C","M","C"],["T"],["T/A/PC","A/PC"]],
"4-4-2":[["P"],["DD","DC","DC","DS"],["M/C","C","E"],["E/W"],["A/PC","A/PC"]],
"4-1-4-1":[["P"],["DD","DC","DC","DS"],["M"],["C/T","T"],["E/W","W"],["A/PC"]],
"4-4-1-1":[["P"],["DD","DC","DC","DS"],["M","C"],["E/W","E/W"],["T/A"],["A/PC"]],
"4-2-3-1":[["P"],["DD","DC","DC","DS"],["M","M/C"],["W/T","T","W/A"],["A/PC"]]
};
const CLASSIC_MODULES={
"3-4-3":[["POR"],["DC","DC","DC"],["CC","CC","CC","CC"],["ATT","ATT","ATT"]],
"3-5-2":[["POR"],["DC","DC","DC"],["CC","CC","CC","CC","CC"],["ATT","ATT"]],
"4-3-3":[["POR"],["DC","DC","DC","DC"],["CC","CC","CC"],["ATT","ATT","ATT"]],
"4-4-2":[["POR"],["DC","DC","DC","DC"],["CC","CC","CC","CC"],["ATT","ATT"]],
"4-5-1":[["POR"],["DC","DC","DC","DC"],["CC","CC","CC","CC","CC"],["ATT"]],
"5-3-2":[["POR"],["DC","DC","DC","DC","DC"],["CC","CC","CC"],["ATT","ATT"]],
"5-4-1":[["POR"],["DC","DC","DC","DC","DC"],["CC","CC","CC","CC"],["ATT"]]
};
let players=[],selected=new Set(JSON.parse(localStorage.getItem('ml_selected')||'[]')),mode=null,moduleName=null,assignments=[],showSelectedOnly=false,dragPlayerId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const currentModules=()=>mode==='classic'?CLASSIC_MODULES:MANTRA_MODULES;
const currentModule=()=>currentModules()[moduleName]||[];
const getPlayer=id=>players.find(p=>String(p.id)===String(id));
const initials=n=>(n||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const norm=r=>String(r||'').trim().toUpperCase();
const roleParts=r=>norm(r).split('/').map(x=>x.trim()).filter(Boolean);
const playerRoles=p=>mode==='classic'?[norm(p.classic)]:((p.roles||[]).map(norm));
const roleMatch=(p,r)=>!!p&&roleParts(r).some(req=>playerRoles(p).some(pr=>norm(pr)===req));
const price=p=>Number(p?.price)||Number(p?.initialPrice)||0;
const image=p=>p?.image||p?.imageUrl||p?.photo||p?.photoUrl||'';
const roleClass=r=>{const x=norm(r);if(x==='P'||x==='POR')return'gk';if(['DD','DC','DS'].includes(x))return'def';if(['M','M/C','C','CC','E','E/W'].includes(x))return'mid';if(['T','T/A','C/T','W','W/A','W/T'].includes(x))return'treq';return'att'};
const save=()=>{localStorage.setItem('ml_selected',JSON.stringify([...selected]));localStorage.setItem('ml_players',JSON.stringify(players));};
const toast=m=>{const e=$('#appToast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2200)};
function renderModuleOptions(){const e=$('#moduleSelect');if(e)e.innerHTML=Object.keys(currentModules()).map(n=>`<option>${n}</option>`).join('');}
function solve(name){const req=currentModule().flat();const pool=players.filter(p=>selected.has(String(p.id)));const out=req.map(r=>({req:r,p:null}));const used=new Set();const ordered=req.map((r,i)=>({r,i,c:pool.filter(p=>roleMatch(p,r)).sort((a,b)=>price(a)-price(b))})).sort((a,b)=>a.c.length-b.c.length);for(const s of ordered){const p=s.c.find(x=>!used.has(String(x.id)));if(p){used.add(String(p.id));out[s.i].p=p}}return{assignments:out,coverage:req.length?Math.round(out.filter(x=>x.p).length/req.length*100):0,missing:out.filter(x=>!x.p).map(x=>x.req),complete:out.every(x=>x.p)}}
function analyze(){return Object.keys(currentModules()).map(module=>{const s=solve(module);return{module,...s,covered:s.assignments.filter(x=>x.p).length}})}
const yFor=rows=>rows.length===4?[82,48,30,16]:rows.length===5?[84,62,43,27,14]:rows.length===6?[85,67,49,34,22,12]:[84,67,50,34,20,11];
function miniSlots(rows){let html='';const ys=yFor(rows);rows.forEach((row,ri)=>row.forEach((r,j)=>{const x=row.length===1?50:10+(80*j/(row.length-1));html+=`<span class="mini-slot ${roleClass(r)}" style="left:${x}%;top:${ys[ri]}%">${r}</span>`}));return html}
function renderGallery(){const grid=$('#moduleGrid');if(!grid)return;const results=new Map(analyze().map(x=>[x.module,x]));const names=Object.keys(currentModules());grid.innerHTML=names.map(name=>{const r=results.get(name),active=name===moduleName;return `<button type="button" class="module-card ${active?'active':''}" data-module="${name}"><div class="module-card-title"><strong>${name}</strong><span>${r.coverage}%</span></div><div class="mini-pitch"><div class="mini-box"></div>${miniSlots(currentModules()[name])}</div><div class="module-card-foot"><span>${r.complete?'✓ Modulo coperto':'Seleziona modulo'}</span><em>${r.covered}/${currentModules()[name].flat().length}</em></div></button>`}).join('');$$('.module-card').forEach(b=>b.onclick=()=>chooseModule(b.dataset.module));$('#compatibleCount').textContent=analyze().filter(x=>x.complete).length;$('#heroModules').textContent=names.length}
function renderPlayers(){const q=($('#playerSearch')?.value||'').toLowerCase().trim();let list=players.filter(p=>[p.name,p.team,p.classic,...(p.roles||[])].join(' ').toLowerCase().includes(q));if(showSelectedOnly)list=list.filter(p=>selected.has(String(p.id)));$('#visibleCount').textContent=`${list.length} visibili`;$('#playerList').innerHTML=list.map(p=>{const id=String(p.id),sel=selected.has(id),im=image(p);return `<button class="player roster-player ${sel?'selected':''}" data-id="${id}" draggable="true"><span class="selection-mark">${sel?'✓':'+'}</span><span class="avatar player-photo">${im?`<img src="${im}" alt="" loading="lazy">`:initials(p.name)}</span><span class="pinfo"><span class="roster-role">${mode==='classic'?p.classic:(p.roles||[])[0]||'—'}</span><span class="pname">${p.name}</span><span class="pmeta"><b>${p.team||'—'}</b> · ${(mode==='classic'?[p.classic]:(p.roles||[])).join(' / ')}</span></span><span class="credit-box"><b>${price(p)}</b><small>FC</small></span></button>`}).join('')||'<div class="empty-list">Nessun giocatore trovato.</div>';$$(".roster-player").forEach(e=>{e.onclick=()=>toggleSelection(e.dataset.id);e.ondragstart=ev=>{ev.dataTransfer.setData('text/player',e.dataset.id)}});$('#squadCount').textContent=`${selected.size}/30`;$('#heroPlayers').textContent=`${selected.size}/30`;$('#heroListone').textContent=players.length;$('#rosterCount').textContent=selected.size;$('#selectedSummary').textContent=`${selected.size} / 30 giocatori`;$('#listMeta').textContent=`${players.length} giocatori · max 30 in rosa`}
function toggleSelection(id){id=String(id);if(selected.has(id)){selected.delete(id);dragPlayerId=null}else{if(selected.size>=30)return toast('Rosa completa: massimo 30 giocatori.');selected.add(id);dragPlayerId=id}save();renderAll()}
function place(id,slot){const p=getPlayer(id),req=currentModule().flat()[slot];if(!p||!req)return;if(!roleMatch(p,req))return toast(`${p.name} non è adattabile a ${req}`);if(!selected.has(String(id))){if(selected.size>=30)return toast('Rosa completa');selected.add(String(id));save()}let a=(assignments.length?assignments:solve(moduleName).assignments).map(x=>({...x}));const old=a.findIndex(x=>x.p&&String(x.p.id)===String(id));if(old>=0)a[old]={req:currentModule().flat()[old],p:null};a[slot]={req,p};assignments=a;dragPlayerId=null;renderAll(false)}
function rolePicker(slotEl){document.querySelector('.role-picker')?.remove();const req=currentModule().flat()[Number(slotEl.dataset.slot)];const list=players.filter(p=>roleMatch(p,req)).sort((a,b)=>price(a)-price(b));const box=document.createElement('div');box.className='role-picker';box.innerHTML=`<div class="role-picker-head"><b>${req}</b><span>${list.length} giocatori adattabili · ordinati per FC</span><button>×</button></div><div class="role-picker-list">${list.map(p=>`<button class="role-option" data-id="${p.id}"><span class="avatar player-photo">${image(p)?`<img src="${image(p)}">`:initials(p.name)}</span><span><b>${p.name}</b><small>${p.team||'—'} · ${(p.roles||[]).join(' / ')}</small></span><strong>${price(p)} FC</strong></button>`).join('')||'<div class="role-empty">Nessun giocatore adattabile</div>'}</div>`;document.body.appendChild(box);const r=slotEl.getBoundingClientRect(),w=Math.min(390,innerWidth-20);box.style.width=w+'px';box.style.left=Math.max(10,Math.min(innerWidth-w-10,r.left+r.width/2-w/2))+'px';box.style.top=Math.max(10,Math.min(innerHeight-520,r.bottom+8))+'px';box.querySelector('button').onclick=()=>box.remove();box.querySelectorAll('.role-option').forEach(b=>b.onclick=()=>{place(b.dataset.id,Number(slotEl.dataset.slot));box.remove()})}
function renderPitch(){if(!moduleName)return;const rows=currentModule(),a=assignments.length?assignments:solve(moduleName).assignments;assignments=a;let i=0,html='';rows.forEach((row,ri)=>row.forEach((req,j)=>{const x=row.length===1?50:12+(76*j/(row.length-1));const p=a[i]?.p;html+=`<div class="slot ${p?'filled':'empty'}" data-slot="${i}" style="left:${x}%;top:${yFor(rows)[ri]}%"><div class="slot-card" draggable="${!!p}"><div class="slot-avatar">${p?(image(p)?`<img src="${image(p)}">`:initials(p.name)):'+'}</div><div class="slot-name">${p?p.name:'Inserisci'}</div><div class="slot-role">${p?(mode==='classic'?p.classic:(p.roles||[]).join(' / ')):req}</div></div></div>`;i++}));$('#pitch').innerHTML=html;$$('.slot').forEach(s=>{s.onclick=()=>dragPlayerId?place(dragPlayerId,Number(s.dataset.slot)):rolePicker(s);s.ondragover=e=>{e.preventDefault();s.classList.add('drag-over')};s.ondragleave=()=>s.classList.remove('drag-over');s.ondrop=e=>{e.preventDefault();place(e.dataTransfer.getData('text/player'),Number(s.dataset.slot))}});$('#moduleTitle').textContent=moduleName;$('#moduleSubtitle').textContent=`${currentModule().flat().length} slot · ${selected.size} giocatori disponibili`;const miss=a.filter(x=>!x.p).length;$('#statusPill').className='status '+(miss?'warn':'good');$('#statusPill').textContent=miss?`${miss} posizioni scoperte`:'Modulo coperto'}
function renderCoverage(){if(!moduleName)return;const a=assignments,req=currentModule().flat();const unique=[...new Set(req)];$('#coverage').innerHTML=unique.map(r=>{const need=req.filter(x=>x===r).length,have=[...selected].map(getPlayer).filter(p=>roleMatch(p,r)).length,pct=Math.min(100,Math.round(have/need*100));return `<div class="coverage-row"><div class="cov-top"><span>${r}</span><b>${have}/${need}</b></div><div class="cov-bar"><div class="cov-fill" style="width:${pct}%"></div></div></div>`}).join('');const miss=a.filter(x=>!x.p).map(x=>x.req);$('#tipBox').innerHTML=`<b>💡 Suggerimento</b><p>${miss.length?`Mancano: <b>${[...new Set(miss)].join(', ')}</b>.`:'La rosa copre tutte le posizioni.'}</p>`}
function renderFormationAnalysis(){const rs=analyze();$('#formationResults').innerHTML=rs.map(r=>`<button class="formation-card ${r.module===moduleName?'active':''}" data-formation="${r.module}"><strong>${r.module}</strong><span>${r.coverage}%</span><small>${r.complete?'11/11 posizioni coperte':`Manca ${r.missing.join(', ')||'—'}`}</small></button>`).join('');$$('.formation-card').forEach(b=>b.onclick=()=>chooseModule(b.dataset.formation))}
function chooseModule(name){moduleName=name;assignments=[];dragPlayerId=null;document.body.classList.remove('placing-player');$('#formationWorkspace').classList.remove('hidden');renderAll();setTimeout(()=>$('#formationWorkspace').scrollIntoView({behavior:'smooth',block:'start'}),20)}
function renderAll(renderModules=true){renderPlayers();if(renderModules)renderGallery();if(moduleName){renderPitch();renderCoverage();renderFormationAnalysis()}else $('#formationWorkspace').classList.add('hidden')}
function setMode(next){mode=next;moduleName=null;assignments=[];selected=new Set(JSON.parse(localStorage.getItem('ml_selected')||'[]'));$('#builderControls').classList.remove('hidden');$('#formatLabel').textContent=next.toUpperCase();renderModuleOptions();renderAll();$('#moduleBrowser').scrollIntoView({behavior:'smooth',block:'start'})}
$$('.mode-choice').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('#changeModeBtn')?.addEventListener('click',()=>$('#modeGate').scrollIntoView({behavior:'smooth'}));
$('#playerSearch')?.addEventListener('input',()=>renderPlayers());$('#allPlayersBtn')?.addEventListener('click',()=>{showSelectedOnly=false;renderPlayers()});$('#selectedPlayersBtn')?.addEventListener('click',()=>{showSelectedOnly=true;renderPlayers()});$('#clearSearch')?.addEventListener('click',()=>{$('#playerSearch').value='';renderPlayers()});$('#selectVisibleBtn')?.addEventListener('click',()=>{document.querySelectorAll('.roster-player').forEach(e=>{const id=e.dataset.id;if(!selected.has(id)&&selected.size<30)selected.add(id)});save();renderAll()});$('#clearSelectionBtn')?.addEventListener('click',()=>{selected.clear();assignments=[];save();renderAll()});$('#shuffleBtn')?.addEventListener('click',()=>{moduleName=null;assignments=[];renderGallery();$('#formationWorkspace').classList.add('hidden');$('#moduleBrowser').scrollIntoView({behavior:'smooth'})});
$('#autoBtn')?.addEventListener('click',()=>{const best=analyze().sort((a,b)=>b.coverage-a.coverage)[0];if(best)chooseModule(best.module)});
$('#exportBtn')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({mode,selected:[...selected],module:moduleName},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mantra-lab.json';a.click();URL.revokeObjectURL(a.href)});
async function boot(){try{players=await window.MantraLabDataProvider.loadPlayers();}catch(e){console.error(e);players=[]}renderAll(false)}
boot();