const modules={
"3-4-3":[["Por"],["Dc","Dc","Dc/B"],["E","M/C","C","E"],["W/A","W/A","A/Pc"]],
"3-4-1-2":[["Por"],["Dc","Dc","Dc/B"],["E","M/C","C","E"],["T"],["A/Pc","A/Pc"]],
"3-4-2-1":[["Por"],["Dc","Dc","Dc/B"],["M","M/C","E/W","E"],["T","T/A"],["A/Pc"]],
"3-5-2":[["Por"],["Dc","Dc","Dc/B"],["E/W","M/C","M","C","E"],["A/Pc","A/Pc"]],
"3-5-1-1":[["Por"],["Dc","Dc","Dc/B"],["E/W","M","C","M","E/W"],["T/A"],["A/Pc"]],
"4-3-3":[["Por"],["Dd","Dc","Dc","Ds"],["M/C","M","C"],["W/A","W/A","A/Pc"]],
"4-3-1-2":[["Por"],["Dd","Dc","Dc","Ds"],["M/C","M","C"],["T"],["A/Pc","A/Pc"]],
"4-4-2":[["Por"],["Dd","Dc","Dc","Ds"],["M/C","C","E","E/W"],["A/Pc","A/Pc"]],
"4-4-1-1":[["Por"],["Dd","Dc","Dc","Ds"],["M","C"],["E/W","E/W"],["T/A"],["A/Pc"]],
"4-2-3-1":[["Por"],["Dd","Dc","Dc","Ds"],["M","M/C"],["W/T","T","W/A"],["A/Pc"]],
"4-1-4-1":[["Por"],["Dd","Dc","Dc","Ds"],["M"],["C/T","T","E/W","W"],["A/Pc"]]
};
const classicModules={"4-3-3":[["P"],["D","D","D","D"],["C","C","C"],["A","A","A"]],"4-4-2":[["P"],["D","D","D","D"],["C","C","C","C"],["A","A"]],"3-4-3":[["P"],["D","D","D"],["C","C","C","C"],["A","A","A"]],"3-5-2":[["P"],["D","D","D"],["C","C","C","C","C"],["A","A"]]};
let players=[],selected=new Set(JSON.parse(localStorage.getItem("ml_selected")||"[]")),mode=null,moduleName=null,assignments=[],showSelectedOnly=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const currentModules=()=>mode==="mantra"?modules:classicModules;
const currentModule=()=>currentModules()[moduleName]||[];
const getPlayer=id=>players.find(p=>String(p.id)===String(id));
const initials=n=>(n||"").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const rolesOf=p=>mode==="mantra"?(p.roles||[]):[p.classic];
const alternatives=r=>String(r).split("/").map(x=>x.trim()).filter(Boolean);
const roleMatch=(p,r)=>!!p&&alternatives(r).some(x=>rolesOf(p).includes(x));
const score=(p,r)=>roleMatch(p,r)?4-(rolesOf(p).length)+(Number(p.price)||0)/1000:999;
const rowY=n=>n<=4?[86,62,38,16].slice(0,n):[88,69,51,33,16].slice(0,n);
const miniClass=r=>{r=alternatives(r)[0].toLowerCase();if(["por","p"].includes(r))return"gk";if(["dd","ds","dc","b","d"].includes(r))return"def";if(["e","m","c"].includes(r))return"mid";if(["t","w"].includes(r))return"treq";return"att"};
function save(){localStorage.setItem("ml_players",JSON.stringify(players));localStorage.setItem("ml_selected",JSON.stringify([...selected]));}
function toast(m){const e=$("#appToast");e.textContent=m;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2200)}
function renderModuleOptions(){const e=$("#moduleSelect");e.innerHTML=Object.keys(currentModules()).map(n=>`<option value="${n}">${n}</option>`).join("");if(moduleName)e.value=moduleName}
function solveModule(name){
 const req=(currentModules()[name]||[]).flat(),pool=players.filter(p=>selected.has(String(p.id)));if(!req.length)return{complete:false,assignments:[],missing:[],coverage:0};
 const slots=req.map((r,i)=>({r,i,ps:pool.filter(p=>roleMatch(p,r)).sort((a,b)=>score(a,r)-score(b,r))})).sort((a,b)=>a.ps.length-b.ps.length),used=new Set(),out={};
 function dfs(i){if(i===slots.length)return true;for(const p of slots[i].ps){const id=String(p.id);if(used.has(id))continue;used.add(id);out[slots[i].i]={req:slots[i].r,p};if(dfs(i+1))return true;used.delete(id);delete out[slots[i].i]}return false}
 const complete=dfs(0);if(!complete){used.clear();for(const s of slots){const p=s.ps.find(x=>!used.has(String(x.id)));out[s.i]={req:s.r,p:p||null};if(p)used.add(String(p.id))}}
 const a=req.map((r,i)=>out[i]||{req:r,p:null});return{complete,assignments:a,missing:a.filter(x=>!x.p).map(x=>x.req),coverage:Math.round(a.filter(x=>x.p).length/req.length*100)}
}
function analyze(){return Object.keys(currentModules()).map(module=>{const s=solveModule(module);return{module,...s,covered:s.assignments.filter(x=>x.p).length}}).sort((a,b)=>b.coverage-a.coverage||a.missing.length-b.missing.length||a.module.localeCompare(b.module))}
function renderGallery(results){
 const grid=$("#moduleGrid"),map=new Map(results.map(x=>[x.module,x]));if(!grid)return;
 grid.innerHTML=Object.keys(currentModules()).map(name=>{const rows=currentModules()[name],r=map.get(name),ys=rowY(rows.length);let slots="";rows.forEach((row,ri)=>row.forEach((req,j)=>{const x=row.length===1?50:12+76*j/(row.length-1);slots+=`<span class="mini-slot ${miniClass(req)}" style="left:${x}%;top:${ys[ri]}%">${req}</span>`}));return`<button class="module-card ${name===moduleName?"active":""} ${r.complete?"complete":""}" data-module="${name}"><div class="module-card-title"><strong>${name}</strong><span>${r.coverage}%</span></div><div class="mini-pitch">${slots}<i class="mini-center-line"></i></div><div class="module-card-foot"><span>${r.complete?"✓ Modulo coperto":r.covered?`Coperti ${r.covered}/11`:"Scegli questo modulo"}</span><em>${r.covered}/11</em></div></button>`}).join("");
 $$(".module-card").forEach(e=>e.onclick=()=>chooseModule(e.dataset.module));$("#compatibleCount").textContent=results.filter(x=>x.complete).length;$("#heroModules").textContent=Object.keys(currentModules()).length
}
function renderPlayers(){
 const q=$("#playerSearch").value.toLowerCase();let list=players.filter(p=>(p.name+" "+p.team+" "+(p.roles||[]).join(" ")+" "+p.classic).toLowerCase().includes(q));if(showSelectedOnly)list=list.filter(p=>selected.has(String(p.id)));
 $("#visibleCount").textContent=`${list.length} visibili`;$("#playerList").innerHTML=list.map(p=>{const id=String(p.id),s=selected.has(id);return`<button class="player ${s?"selected":""}" data-id="${id}" draggable="true"><span class="selection-mark">${s?"✓":"+"}</span><span class="avatar">${initials(p.name)}</span><span class="pinfo"><span class="pname">${p.name}</span><span class="pmeta">${p.team} · ${mode==="mantra"?(p.roles||[]).join(" / "):p.classic}</span></span><span class="roles">${p.price||"—"}</span></button>`}).join("")||`<div class="empty-list">${showSelectedOnly?"Nessun giocatore selezionato.":"Nessun giocatore trovato."}</div>`;
 $$(".player").forEach(e=>{e.ondragstart=x=>{x.dataTransfer.setData("text/player",e.dataset.id);x.dataTransfer.effectAllowed="copy"};e.onclick=()=>toggleSelection(e.dataset.id)});
 $("#squadCount").textContent=`${selected.size}/30`;$("#heroPlayers").textContent=`${selected.size}/30`;$("#heroListone").textContent=players.length;$("#rosterCount").textContent=selected.size;$("#selectedSummary").textContent=`${selected.size} / 30 giocatori`;$("#selectionHint").textContent=selected.size>=30?"Rosa completa":selected.size?`${30-selected.size} slot disponibili`:"Trascina i giocatori sul campo";$("#listMeta").textContent=`${players.length} giocatori · max 30 in rosa`;$("#allPlayersBtn").classList.toggle("active",!showSelectedOnly);$("#selectedPlayersBtn").classList.toggle("active",showSelectedOnly)
}
function toggleSelection(id){id=String(id);if(selected.has(id))selected.delete(id);else{if(selected.size>=30)return toast("Rosa completa: massimo 30 giocatori.");selected.add(id);window.__dragPlayerId=id;document.body.classList.add("placing-player")}save();renderAll()}
function fillRemaining(base){const req=currentModule().flat(),used=new Set(base.filter(x=>x&&x.p).map(x=>String(x.p.id))),out=base.map(x=>x||null);for(const [i,r] of req.entries())if(!out[i]||!out[i].p){const p=players.filter(x=>selected.has(String(x.id))&&!used.has(String(x.id))&&roleMatch(x,r)).sort((a,b)=>score(a,r)-score(b,r))[0];out[i]={req:r,p:p||null};if(p)used.add(String(p.id))}return out}
function placePlayerOnSlot(id,i){id=String(id);const p=getPlayer(id),req=currentModule().flat()[i];if(!p||!req)return;if(!selected.has(id)){if(selected.size>=30)return toast("Rosa completa: massimo 30 giocatori.");selected.add(id);save()}if(!roleMatch(p,req))return toast(`${p.name}: non compatibile con ${req}`);let base=(window.__manualAssignments||solveModule(moduleName).assignments).map(x=>({...x})),old=base.findIndex(x=>x.p&&String(x.p.id)===id),displaced=base[i]?.p||null;if(old>=0)base[old]={req:currentModule().flat()[old],p:null};base[i]={req,p};if(displaced&&old>=0&&String(displaced.id)!==id&&roleMatch(displaced,currentModule().flat()[old]))base[old]={req:currentModule().flat()[old],p:displaced};window.__manualAssignments=fillRemaining(base);assignments=window.__manualAssignments;window.__dragPlayerId=null;document.body.classList.remove("placing-player");renderPitchFromAssignments();renderCoverage();renderFormationAnalysis(analyze())}
function bindSlots(){$$(".slot").forEach(e=>{e.ondragover=x=>{x.preventDefault();e.classList.add("drag-over")};e.ondragleave=()=>e.classList.remove("drag-over");e.ondrop=x=>{x.preventDefault();e.classList.remove("drag-over");const id=x.dataTransfer.getData("text/player");if(id)placePlayerOnSlot(id,+e.dataset.slot)};e.onclick=()=>{const id=window.__dragPlayerId;if(id)placePlayerOnSlot(id,+e.dataset.slot)}});$$(".slot-card[draggable='true']").forEach(e=>e.ondragstart=x=>{x.dataTransfer.setData("text/player",e.dataset.player);x.dataTransfer.effectAllowed="move"})}
function renderPitch(){if(!moduleName)return;const s=solveModule(moduleName);assignments=window.__manualAssignments||s.assignments;renderPitchFromAssignments()}
function renderPitchFromAssignments(){const rows=currentModule(),ys=rowY(rows.length);let html="",i=0;rows.forEach((row,ri)=>row.forEach((req,j)=>{const x=row.length===1?50:15+70*j/(row.length-1),p=assignments[i]?.p;html+=`<div class="slot ${p?"filled":"empty"}" data-slot="${i}" style="left:${x}%;top:${ys[ri]}%"><div class="slot-card" draggable="${!!p}" data-player="${p?p.id:""}"><div class="slot-avatar">${p?initials(p.name):"＋"}</div><div class="slot-name">${p?p.name:"Inserisci"}</div><div class="slot-role">${p?(mode==="mantra"?(p.roles||[]).join(" / "):p.classic):req}</div></div></div>`;i++}));$("#pitch").innerHTML=html;bindSlots();const missing=assignments.filter(x=>!x.p);$("#statusPill").className="status "+(missing.length?"warn":"good");$("#statusPill").textContent=missing.length?`${missing.length} posizioni scoperte`:"Modulo coperto";$("#benchChips").innerHTML=[...selected].map(getPlayer).filter(Boolean).map(p=>`<button class="chip player-chip" draggable="true" data-player="${p.id}">${p.name}<span>${mode==="mantra"?(p.roles||[]).join("/"):p.classic}</span></button>`).join("")||'<span class="chip">Nessun giocatore selezionato</span>';$$(".player-chip").forEach(e=>{e.ondragstart=x=>{x.dataTransfer.setData("text/player",e.dataset.player);x.dataTransfer.effectAllowed="move"};e.onclick=()=>{window.__dragPlayerId=e.dataset.player;document.body.classList.add("placing-player")}})}
function renderCoverage(){if(!moduleName)return;const req=currentModule().flat(),u=[...new Set(req)];$("#coverage").innerHTML=u.map(r=>{const need=req.filter(x=>x===r).length,have=[...selected].map(getPlayer).filter(p=>roleMatch(p,r)).length,p=Math.min(100,have/need*100),c=p>=100?"":p>=50?"warn":"bad";return`<div class="coverage-row"><div class="cov-top"><span>${r}</span><b>${have}/${need}</b></div><div class="cov-bar"><div class="cov-fill ${c}" style="width:${p}%"></div></div></div>`}).join("");const miss=assignments.filter(x=>!x.p).map(x=>x.req);$("#tipBox").innerHTML=`<b>💡 Suggerimento</b><p>${miss.length?`Ti mancano ${miss.length} slot: <b>${[...new Set(miss)].join(", ")}</b>.`:"La rosa copre tutte le posizioni. Puoi spostare i giocatori direttamente sul campo."}</p>`;$("#moduleTitle").textContent=moduleName;$("#moduleSubtitle").textContent=`${req.length} slot · ${selected.size} giocatori disponibili`}
function renderFormationAnalysis(results){
  $("#formationResults").innerHTML=results.map((r,i)=>{const detail=r.complete?"✓ 11/11 posizioni coperte":"Manca: "+([...new Set(r.missing)].join(" · ")||"—");return`<button class="formation-card ${r.module===moduleName?"active":""}" data-formation="${r.module}"><div class="formation-rank">${String(i+1).padStart(2,"0")}</div><div class="formation-main"><strong>${r.module}</strong><span>${r.complete?"COMPATIBILE":"PARZIALE"}</span><div class="formation-${r.complete?"ok":"missing"}">${detail}</div></div><div class="formation-pct">${r.coverage}%</div></button>`}).join("")||'<div class="empty-analysis">Scegli una rosa per analizzare i moduli.</div>';
  $$(".formation-card").forEach(e=>e.onclick=()=>chooseModule(e.dataset.formation));
}
function renderSquad(){$("#squadGrid").innerHTML=[...selected].map(getPlayer).filter(Boolean).map(p=>`<div class="squad-card card"><h3>${p.name}</h3><p>${p.team} · Quotazione ${p.price}</p><div class="role-tags"><span class="role-tag">${p.classic}</span>${(p.roles||[]).map(r=>`<span class="role-tag">${r}</span>`).join("")}</div></div>`).join("")||'<div class="card squad-card"><h3>Rosa vuota</h3><p>Vai nel Builder e aggiungi i giocatori.</p></div>'}
function chooseModule(n){moduleName=n;window.__manualAssignments=null;window.__dragPlayerId=null;document.body.classList.remove("placing-player");$("#formationWorkspace").classList.remove("hidden");$("#moduleSelect").value=n;renderAll();setTimeout(()=>$("#formationWorkspace").scrollIntoView({behavior:"smooth",block:"start"}),20)}
function renderAll(){renderPlayers();renderSquad();if(mode){const r=analyze();renderModuleGallery(r);renderFormationAnalysis(r)}if(moduleName){renderPitch();renderCoverage()}else{$("#formationWorkspace").classList.add("hidden");$("#formationResults").innerHTML='<div class="empty-analysis">Scegli un modulo per aprire il campo.</div>'}}
async function loadPlayers(){try{if(localStorage.getItem("ml_custom_players")==="1"){const s=JSON.parse(localStorage.getItem("ml_players")||"[]");if(s.length){players=s;return}}players=await window.MantraLabDataProvider.loadPlayers();localStorage.setItem("ml_players",JSON.stringify(players))}catch(e){players=JSON.parse(localStorage.getItem("ml_players")||"[]")||[];toast("Impossibile caricare il listone locale.")}selected=new Set([...selected].map(String).filter(id=>players.some(p=>String(p.id)===id)).slice(0,30));save()}
$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$("#"+b.dataset.view+"View").classList.remove('hidden')});
$$('.mode-choice').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;moduleName=null;window.__manualAssignments=null;$("#builderControls").classList.remove('hidden');$("#formatLabel").textContent=mode.toUpperCase();renderModuleOptions();renderAll();$("#moduleBrowser").scrollIntoView({behavior:'smooth',block:'start'})});
$("#changeModeBtn").onclick=()=>$("#modeGate").scrollIntoView({behavior:'smooth',block:'start'});
$("#moduleSelect").onchange=e=>chooseModule(e.target.value);$("#playerSearch").oninput=renderPlayers;$("#clearSearch").onclick=()=>{$("#playerSearch").value="";renderPlayers()};$("#allPlayersBtn").onclick=()=>{showSelectedOnly=false;renderPlayers()};$("#selectedPlayersBtn").onclick=()=>{showSelectedOnly=true;renderPlayers()};
$("#selectVisibleBtn").onclick=()=>{const q=$("#playerSearch").value.toLowerCase();for(const p of players.filter(x=>(x.name+" "+x.team+" "+(x.roles||[]).join(" ")+" "+x.classic).toLowerCase().includes(q))){if(selected.size>=30)break;if(!selected.has(String(p.id)))selected.add(String(p.id))}save();renderAll()};$("#clearSelectionBtn").onclick=()=>{selected.clear();window.__manualAssignments=null;save();renderAll()};$("#autoBtn").onclick=()=>{if(!mode)return toast("Scegli prima MANTRA o CLASSIC.");const r=analyze();chooseModule(r[0].module)};$("#shuffleBtn").onclick=()=>{const n=Object.keys(currentModules()),i=n.indexOf(moduleName);chooseModule(n[(i+1)%n.length])};$("#resetSquad").onclick=()=>{if(confirm("Svuotare la rosa virtuale?")){selected.clear();window.__manualAssignments=null;save();renderAll()}};
$("#exportBtn").onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({players,selected:[...selected],mode,moduleName},null,2)],{type:'application/json'}));a.download='mantra-lab-rosa.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("#importInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const t=r.result;if(f.name.endsWith('.csv')){players=window.MantraLabDataProvider.parseCsv(t).map(x=>({id:String(x.id),name:x.name,team:x.team||'',classic:x.classic||'',roles:String(x.roles||'').split(/[|;]/).filter(Boolean),price:Number(x.price)||0,initialPrice:Number(x.initialPrice)||0,fvm:Number(x.fvm)||0,fvmMantra:Number(x.fvmMantra)||0})).filter(x=>x.name)}else{const d=JSON.parse(t);if(Array.isArray(d.players))players=d.players;if(Array.isArray(d.selected))selected=new Set(d.selected.map(String).slice(0,30));if(d.mode)mode=d.mode;if(d.moduleName)moduleName=d.moduleName}localStorage.setItem('ml_custom_players','1');save();if(!mode)mode='mantra';if(!moduleName)moduleName=Object.keys(currentModules())[0];$("#builderControls").classList.remove('hidden');renderModuleOptions();renderAll()}catch(err){alert('File non valido. Usa CSV id,name,team,classic,roles,price oppure il JSON esportato.')}};r.readAsText(f)};
(async()=>{await loadPlayers();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})();
